src/feedback/urls.py
# coding=utf-8

from django.conf.urls import include

import feedback.views.public
import feedback.views.veranstalter
from feedback.views.public_class_view import VeranstaltungsDeadlines
import feedback.views.intern
import feedback.views.intern.vv
import feedback.views.intern.auth
from django.views.decorators.csrf import csrf_exempt
import django.contrib.auth.views
from django.urls import reverse_lazy, re_path
from django.conf import settings
from feedback.views.veranstalter import VeranstalterWizard
from django.utils.translation import get_language

default_redirect = f'/{get_language()}/veranstalter/'

# allgemeine Views
urlpatterns = [
    re_path(r'^$', feedback.views.redirect, {'redirect_to': default_redirect}, name="default"),
]

# öffentliche Views
urlpatterns += [
    re_path(r'^ergebnisse/(?P<vid>\d+)/$', feedback.views.public.veranstaltung, name='public-veranstaltung'),
    re_path(r'^ergebnisse/(?P<vid>\d+)/(?P<seminar>seminar)/$', feedback.views.public.veranstaltung, name='public-veranstaltung'),
    re_path(r'^ergebnisse/$', feedback.views.public.index, name='public-results'),
]

urlpatterns += [re_path(r'^deadlines/$', VeranstaltungsDeadlines.as_view(), name='Deadlines'),
                re_path(r'^barcodedrop/$', csrf_exempt(feedback.views.public.barcodedrop), name='barcodedrop'),]


# Veranstalter-Views
urlpatterns += [
    re_path(r'^veranstalter/login/$', feedback.views.veranstalter.login, name='veranstalter-login'),
    re_path(r'^veranstalter/logout/$',
        django.contrib.auth.views.LogoutView.as_view(),
        {'template_name': "veranstalter/logout.html"},
        name='veranstalter-logout'),

    re_path(r'^veranstalter/bestellung', VeranstalterWizard.as_view(), name='veranstalter-bestellung'),
    re_path(r'^veranstalter/', feedback.views.veranstalter.veranstalter_dashboard, name='veranstalter-index')
]

# interne Views
urlpatterns += [
    re_path(r'^intern/uebersicht/$', feedback.views.intern.index, name='intern-index'),
    re_path(r'^intern/sendmail/$', feedback.views.intern.sendmail, name='sendmail'),
    re_path(r'^intern/questions_list/$', feedback.views.intern.freie_frage_veranstaltungen, name='free-questions'),
    re_path(r'^intern/export_veranstaltungen/$', feedback.views.intern.export_veranstaltungen, name='export_veranstaltungen'),
    re_path(r'^intern/generate_letters/$', feedback.views.intern.generate_letters, name='generate_letters'),
    re_path(r'^intern/import_ergebnisse/$', feedback.views.intern.import_ergebnisse, name='import_ergebnisse'),
    re_path(r'^intern/status_final/$', feedback.views.intern.CloseOrderFormView.as_view(), name='status_final'),
    re_path(r'^intern/sync_ergebnisse/$', feedback.views.intern.sync_ergebnisse, name='sync_ergebnisse'),
    re_path(r'^intern/fragebogensprache/$', feedback.views.intern.fragebogensprache, name='fragebogensprache'),
    re_path(r'^intern/lange_ohne_evaluation/$', feedback.views.intern.lange_ohne_evaluation, name='lange_ohne_evaluation'),
    re_path(r'^intern/ergebnisse/$', feedback.views.intern.ergebnisse, name='intern-ergebnisse'),
    re_path(r'^intern/tans/$', feedback.views.intern.ProcessTANs.as_view(),
    name='process-tans'),
]

# interne Views: Vorlesungsverzeichnis
urlpatterns += [
    re_path(r'^intern/import_vv/$', feedback.views.intern.vv.import_vv, name='import_vv'),
    re_path(r'^intern/import_vv_edit/$', feedback.views.intern.vv.import_vv_edit, name='import_vv_edit'),
    re_path(r'^intern/import_vv_edit_users/$', feedback.views.intern.vv.PersonFormView.as_view(),
        name='import_vv_edit_users'),
    re_path(r'^intern/import_vv_edit_users/(?P<pk>\d+)/$', feedback.views.intern.vv.PersonFormUpdateView.as_view(),
        name='import_vv_edit_users_update'),
    re_path(r'^intern/import_vv_edit_users/(?P<pk>\d+)/namecheck/$', feedback.views.intern.vv.SimilarNamesView.as_view(),
        name='import_vv_edit_users_update_namecheck')
]

# interne Views: Authentifizierung
urlpatterns += [
    re_path(r'^intern/rechte_uebernehmen/$', feedback.views.intern.auth.rechte_uebernehmen, name='rechte-uebernehmen'),
    re_path(r'^intern/rechte_zuruecknehmen/$', feedback.views.intern.auth.rechte_zuruecknehmen, name='rechte_zuruecknehmen'),
    re_path(r'^intern/auth_user/$', feedback.views.intern.auth.auth_user, name='auth-user'),
    re_path(r'^intern/$', feedback.views.intern.auth.login, name='auth-login'),
]

# Logout
urlpatterns += [
    re_path(r'^logout/$', django.contrib.auth.views.LogoutView.as_view(), {'next_page': reverse_lazy('feedback:public-results')}, name='logout'),
]


if settings.DEBUG:
    # Ausschließlich in der Entwicklung nötig, damit statische Dateien (JS, CSS, Bilder...)
    # angezeigt werden. Im Server-Betrieb kümmert sich Apache darum.
    urlpatterns += [
        re_path(r'^d120de/(?P<tail>.*)$', feedback.views.redirect, {'redirect_to': 'http://www.d120.de/d120de/'}),
    ]

src/urls.py
# coding=utf-8

from django.conf.urls import include
from django.contrib import admin
from django.contrib.auth.models import User

from django.urls import re_path, reverse_lazy, path
from django.conf.urls.i18n import i18n_patterns
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

from allauth.account.decorators import secure_admin_login

# Admin-Seiten konfigurieren
# admin.site.unregister((User, Group))

# this is a workaround as admin sites doesn't use allauth, see: https://docs.allauth.org/en/latest/common/admin.html
admin.autodiscover()
admin.site.login = secure_admin_login(admin.site.login)

urlpatterns = i18n_patterns(
    path('accounts/', include('allauth.urls')),
)

urlpatterns += [
    re_path(r'^$', RedirectView.as_view(url=reverse_lazy("feedback:default"), permanent=True), name='no-path'),
]

# Datenbank-Admin und Entwicklerdoku
urlpatterns += i18n_patterns(
    # Muss in dieser Reihenfolge stehen bleiben, da sonst /doc nicht funktioniert!
    re_path(r'^intern/admin/doc/', include('django.contrib.admindocs.urls')),
    re_path(r'^intern/admin/', admin.site.urls),
    re_path(r'^', include(("feedback.urls", "feedback"), namespace="feedback")),
)

urlpatterns += staticfiles_urlpatterns()

if not settings.DEBUG :
    # don't forget to put sample favicon.ico in static files
    urlpatterns += [path('favicon.ico', RedirectView.as_view(url='/feedback/static/img/favicon.ico', permanent=True))]

if not settings.TESTING and settings.DEBUG :
    # avoided directly using debug_toolbar.urls(), as importing caused error in django-debug-toolbar v6.0.0 
    # see https://github.com/django-commons/django-debug-toolbar/issues/2167
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

src/feedback/models/base.py
# coding=utf-8


import random

from django.db import models
from django.utils.translation import gettext_lazy as _
from django.db.utils import OperationalError
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.db.models import Q

from feedback.tools import ean_checksum_calc, ean_checksum_valid
from django.contrib.auth.models import User

from django.utils import formats

import datetime


class Semester(models.Model):
    """Repräsentiert ein Semester der TUD."""
    FRAGEBOGEN_CHOICES = (
        ('2008', 'Fragebogen 2008'),
        ('2009', 'Fragebogen 2009'),
        ('2012', 'Fragebogen 2012'),
        ('2016', 'Fragebogen 2016'),
        ('2020', 'Fragebogen 2020'),
        ('2025', 'Fragebogen 2025'),
    )
    SICHTBARKEIT_CHOICES = (
        ('ADM', _('Administratoren')),
        ('VER', _('Veranstalter')),
        ('ALL', _('alle (öffentlich)')),
    )

    semester = models.IntegerField(help_text='Aufbau: YYYYS, wobei YYYY = Jahreszahl und S = Semester (0=SS, 5=WS).',
                                   unique=True)
    fragebogen = models.CharField(max_length=5, choices=FRAGEBOGEN_CHOICES, verbose_name=_("Fragebogen"),
                                  help_text=_('Verwendete Version des Fragebogens.'))
    sichtbarkeit = models.CharField(max_length=3, choices=SICHTBARKEIT_CHOICES, verbose_name=_("Sichtbarkeit"),
                                    help_text=_('Sichtbarkeit der Evaluationsergebnisse.<br /><em>{s1}:</em> nur für Mitglieder des Feedback-Teams<br /><em>{s2}:</em> Veranstalter und Mitglieder des Feedback-Teams<br /><em>{s3}:</em> alle (beschränkt auf das Uninetz)<br />').format(s1=SICHTBARKEIT_CHOICES[0][1],s2=SICHTBARKEIT_CHOICES[1][1],s3=SICHTBARKEIT_CHOICES[2][1])
                                    )
    vollerhebung = models.BooleanField(default=False, verbose_name=_("Vollerhebung"))
    standard_ergebnisversand = models.DateField(null=True, blank=True, verbose_name=_('Ergebnisversand'), help_text=_('Standarddatum für den Ergebnisversand'))

    def _format_generic(self, ss, ws, space, modulus):
        sem = self.semester // 10
        if (modulus > 0):
            sem = sem % modulus

        if self.semester % 10 == 0:
            return '%s%s%d' % (ss, space, sem)
        else:
            return '%s%s%d/%d' % (ws, space, sem, sem + 1)

    def _format(self, ss, ws):
        return self._format_generic(ss, ws, ' ', 0)

    def short(self):
        return self._format('SS', 'WS')

    def long(self):
        return self._format('Sommersemester', 'Wintersemester')

    def evasys(self):
        return self._format_generic('SS', 'WS', '', 100)

    def last_Auswertungstermin(self):
        """Letzter Tag der als Auswertungstermin angegeben werden kann"""
        year = 0
        month = 0
        day = 15
        # Sommersemester
        if self.semester % 10 == 0:
            year = self.semester / 10
            month = 10
        # Wintersemester
        else:
            year = (self.semester / 10) + 1
            month = 4

        return datetime.datetime(int(year), int(month), int(day))

    def last_Auswertungstermin_to_late_human(self):
        """Der erste Tag der nach dem letzten Auswertungstermin liegt formatiert"""
        toLateDate = self.last_Auswertungstermin() + datetime.timedelta(days=1)
        return formats.date_format(toLateDate, 'DATE_FORMAT')

    def auswertungstermin_years(self):
        """Die Jahre in denen der Auswertungstermin liegen kann"""
        return self.last_Auswertungstermin().year,

    def __str__(self):
        return self.long()

    class Meta:
        verbose_name = 'Semester'
        verbose_name_plural = 'Semester'
        ordering = ['-semester']
        app_label = 'feedback'

    @staticmethod
    def current():
        try:
            return Semester.objects.order_by('-semester')[0]
        except IndexError:
            return None
        except OperationalError:
            return None


class Fachgebiet(models.Model):
    """Repräsentiert ein Fachgebiet für das FB20"""
    name = models.CharField(max_length=80)
    kuerzel = models.CharField(max_length=10)

    @staticmethod
    def get_fachgebiet_from_email(email):
        """
        Gibt ein Fachgebiet anhand einer E-Mail Adresse zurück
        :param email: E-Mail String
        :return: Fachgebiet
        """
        try:
            suffix = email.split('@')[-1]
            return EmailEndung.objects.get(domain=suffix).fachgebiet
        except Exception:
            return None

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Fachgebiet')
        verbose_name_plural = _('Fachgebiete')
        app_label = 'feedback'


class EmailEndung(models.Model):
    """Repräsentiert alle Domains die für E-Mails von Veranstaltern verwendet werden"""
    fachgebiet = models.ForeignKey(Fachgebiet,
                                   blank=True,
                                   verbose_name=_("Fachgebiet"),
                                   help_text=_("Hier soll der Domainname einer Email-Adresse eines Fachgebiets stehen."),
                                   on_delete=models.CASCADE)
    domain = models.CharField(max_length=150,
                              null=True)

    def __str__(self):
        return self.domain

    class Meta:
        verbose_name = _('Fachgebiet Emailendung')
        verbose_name_plural = _('Fachgebiet Emailendungen')
        app_label = 'feedback'


class FachgebietEmail(models.Model):
    """Repräsentiert die E-Mail Domänen für die jeweiligen Fachgebiete des FBs 20."""
    fachgebiet = models.ForeignKey(Fachgebiet, related_name='fachgebiet', verbose_name=_("Fachgebiet"), on_delete=models.CASCADE)
    email_sekretaerin = models.EmailField(blank=True)

    class Meta:
        verbose_name = _('Fachgebiet Email')
        verbose_name_plural = _('Fachgebiet Emails')
        app_label = 'feedback'


class Person(models.Model):
    """Repräsentiert eine Person der TUD aus dem FB20."""
    GESCHLECHT_CHOICES = (
        ('', ''),
        ('m', _('Herr')),
        ('w', _('Frau')),
    )

    GESCHLECHT_EVASYS_XML = {
        '': '',
        'm': 'm',
        'w': 'f',
    }

    geschlecht = models.CharField(max_length=1, choices=GESCHLECHT_CHOICES, blank=True, verbose_name=_('Anrede'))
    vorname = models.CharField(_('first name'), max_length=30, blank=True)
    nachname = models.CharField(_('last name'), max_length=30, blank=True)
    email = models.EmailField(_('E-Mail'), blank=True)
    anschrift = models.CharField(_('anschrift'), max_length=80, blank=True,
                                 help_text=_('Tragen Sie bitte nur die Anschrift ohne Namen ein, '
                                           'da der Name automatisch hinzugefügt wird.'))
    fachgebiet = models.ForeignKey(Fachgebiet, verbose_name=_("Fachgebiet"), null=True, blank=True, on_delete=models.CASCADE)

    def full_name(self):
        return '%s %s' % (self.vorname, self.nachname)

    def get_evasys_key(self):
        return "pe-%s" % self.id

    def get_evasys_geschlecht(self):
        return Person.GESCHLECHT_EVASYS_XML[self.geschlecht]

    def __str__(self):
        return '%s, %s' % (self.nachname, self.vorname)

    def printable(self) -> bool:
        """ Check whether the user has all required fields for printing (e.g. for generating the stickers)
        """
        return self.vorname != "" and self.nachname != "" and self.email != "" and self.anschrift != ""

    class Meta:
        verbose_name = _('Person')
        verbose_name_plural = _('Personen')
        ordering = 'nachname', 'vorname'
        app_label = 'feedback'

    @staticmethod
    def create_from_import_person(ip):
        """
        Erstellt Personen aus dem Import
        :param ip: die importierte Person
        :return: Person
        """
        # Prüfen, ob Benutzer existiert
        try:
            return Person.objects.filter(vorname=ip.vorname, nachname=ip.nachname)[0]
        except (Person.DoesNotExist, IndexError):
            try:
                return AlternativVorname.objects.filter(vorname=ip.vorname).get().person
            except (AlternativVorname.DoesNotExist, IndexError):
                return Person.objects.create(vorname=ip.vorname, nachname=ip.nachname)

    @staticmethod
    def persons_to_edit(semester=None):
        """
        Gibt die Personen zurück, die noch bearbeitet werden müssen.
        :param semester: bei None, das aktuelle Semester, ansonsten das Angegebene.
        :return: Person
        """
        if semester is None:
            semester = Semester.current()
        return Person.objects.filter(Q(geschlecht='') | Q(email=''), veranstaltung__semester=semester)\
            .order_by('id').distinct()

    @staticmethod
    def all_edited_persons():
        """
        Gibt alle Personen zurück, die schon bearbeitet wurden.
        :return: Person
        """
        return Person.objects.filter(~Q(geschlecht='') & ~Q(email='')).order_by('id').distinct()

    @staticmethod
    def persons_with_similar_names(vorname, nachname):
        """
        Gibt alle Personen zurück, die sich im Namen ähneln.
        :param vorname: String
        :param nachname: String
        :return: Person
        """
        return Person.all_edited_persons().filter(vorname__startswith=vorname, nachname=nachname)

    @staticmethod
    def veranstaltungen(person):
        """
        Gibt die Veranstaltungen einer Person zurück.
        :param person: Person
        :return: Veranstaltung
        """
        return Veranstaltung.objects.filter(veranstalter=person)

    @staticmethod
    def replace_veranstalter(new, old):
        """
        Ersetzt einen "alten" Veranstalter durch einen "neuen".
        Zum Beispiel wenn Dozenten sich beim Namen ähneln und dementsprechend identisch sind.

src/templates/intern/import_vv_edit_users.html
{% extends "bestellung_base.html" %}
{% load i18n %}
{% block title %}{% translate "Personendaten vervollständigen" %}{% endblock %}

{% block content %}
    <h1>{% translate "Personendaten vervollständigen" %}</h1>

    {% if persons %}
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h2>{% blocktranslate %}Es sind noch {{ persons.count }} Personendaten zu bearbeiten.{% endblocktranslate %}</h2>

                {% for p in persons %}
                            <h2>
                                <a href="{% url 'feedback:import_vv_edit_users_update' pk=p.id %}">
                                    {{p.full_name}}
                                </a>
                            </h2>
                {% endfor %}
        </form>

    {% else %}
        <p>{% translate "Alle Veranstalter des aktuellen Semesters haben vollständige Personendaten." %}</p>
    {% endif %}
{% endblock %}

src/templates/intern/import_vv_edit_users_namecheck.html
{% extends "bestellung_base.html" %}
{% load i18n %}
{% block title %}{% translate "Personendaten vervollständigen" %}{% endblock %}
{% block content %}
    <h1>{% translate "Personendaten vervollständigen" %}</h1>
    {% with similar_person.0 as old %}
    {% with person_new as new %}
         <div style="width: 100%; display: table;">
            <div style="display: table-row">
                <div style="width: 50%; display: table-cell;">
                    <h2>{% translate "Die ähnliche Person" %}</h2>
                    <p><b>{% translate "Name: " %}</b>{{ old.full_name }}</p>
                    <p><b>{% translate "E-Mail: " %}</b>{{ old.email }}</p>
                    <br>
                    <h2>{% translate "Lehrveranstaltungen" %}</h2>
                    {% for v in old_veranstaltungen %}
                        <p>{{ v.name }} &nbsp; {{ v.semester }}</p>
                    {% endfor %}
                </div>

                <div style="display: table-cell;">
                    <h2>{% translate "Die neue Person" %}</h2>
                    <p><b>{% translate "Name: " %}</b>{{ new.full_name }}</p>
                    <p><b>{% translate "E-Mail: " %}</b>{{ new.email }}</p>
                    <br>
                    <h2>{% translate "Lehrveranstaltungen" %}</h2>
                    {% for v in new_veranstaltungen %}
                        <p>{{ v.name }} &nbsp; {{ v.semester }}</p>
                    {% endfor %}
                </div>
            </div>
        </div>

        <br>
        <form action="" method="post">
            {% csrf_token %}
            <input type="hidden" name="id_old" value="{{ old.id }}" />
            <input type="hidden" name="id_new" value="{{ new.id }}" />
            <input type="submit" name="similar" value="{% translate "Zusammenführen" %}" />
        </form>
        <br>
        <input type="button" name="not_similar" value="{% translate "Ignorieren" %}"
            onclick="location.href='{% url 'feedback:import_vv_edit_users_update' pk=new.id %}'"/>

        <br><br>
        <p><a href="{% url 'feedback:import_vv_edit_users' %}">{% translate "zurück zu Personendaten" %}</a></p>
    {% endwith %}
    {% endwith %}
{% endblock %}

src/templates/intern/import_vv_edit_users_update.html
{% extends "bestellung_base.html" %}
{% load i18n %}

{% block title %}{% translate "Personendaten vervollständigen" %}{% endblock %}

{% block content %}
    <h1>{% translate "Personendaten vervollständigen" %}</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ formset.management_form }}
        <h2>{% blocktranslate %}Es sind noch {{ person.persons_to_edit.count }} Personendaten zu bearbeiten.{% endblocktranslate %}</h2>
        <h2>{{ person.full_name }}</h2>
        <h2><a href="http://www.google.com/search?q={{person.full_name}}+tu+darmstadt" target="_blank>">
            {% translate "Auf Google suchen." %}</a></h2>

        {% if view.has_similar_name %}
            <p><a style="color: red" href="{% url 'feedback:import_vv_edit_users_update_namecheck' pk=person.id %}">
                {% translate "Es existiert eine Person, die ähnlich zu dieser ist." %}</a></p>
        {% else %}
            <p></p>
        {% endif %}

        {{ form.as_p }}
        <div>
            {% if view.get_id.1 %}
                <input type="button" name="back" value="{% translate "Zurück" %}"
                       onclick="location.href='{% url 'feedback:import_vv_edit_users_update' pk=view.get_id.1 %}'"/>&nbsp;
            {% else %}
                <input type="button" name="back" value="{% translate "Zurück" %}" disabled="disabled" />&nbsp;
            {% endif %}

            {% if view.get_id.0 %}
                <input type="button" name="jump" value="{% translate "Überspringen" %}"
                       onclick="location.href='{% url 'feedback:import_vv_edit_users_update' pk=view.get_id.0 %}'"/>&nbsp;
            {% else %}
                <input type="button" name="jump" value="{% translate "Überspringen" %}" disabled="disabled" />&nbsp;
            {% endif %}
            <input type="submit" name="submit" value="{% translate "Speichern & Weiter" %}" />
        </div>
    </form>
    <br>
    <p><a href="{% url 'feedback:import_vv_edit_users' %}">{% translate "zurück zu Personendaten" %}</a></p>
{% endblock %}

src/templates/intern/index.html
{% extends "bestellung_base.html" %}
{% load i18n %}
{% load static %}
{% block title %}
    {% translate "Interner Bereich" %}
{% endblock %}

{% block content %}
    <h1>{% translate "Interner Bereich" %}</h1>
    <ul>
        <li><a href="{% url 'admin:index' %}" target="_blank">{% translate "Verwaltung der Daten" %}</a></li>
        <li><a href="{% url 'feedback:rechte-uebernehmen' %}">{% translate "zu Veranstalter-Account wechseln" %}</a></li>
        <li><a href="{% url 'feedback:sendmail' %}">{% translate "Mail an Veranstalter verschicken" %}</a></li>
        <li><a href="{% url 'feedback:fragebogensprache' %}">{% translate "Zuordnung Veranstaltungen zu Fragebogensprache" %}</a></li>
        <li><a href="{% url 'feedback:lange_ohne_evaluation' %}">{% translate "Veranstaltungen die lange nicht mehr evaluiert wurden" %}</a></li>
        <li><a href="{% url 'feedback:free-questions' %}">{% translate "Liste der Veranstaltungen mit freien Fragen" %}</a></li>
        <li>
            <form action = "{% url 'feedback:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-link p-0" style="color: #009D81;">{% translate "Ausloggen" %}</button>
            </form>
        </li>
    </ul>
    <h3>{% translate "Status der Rückmeldungen durch die Veranstalter" %}</h3>
    <p>{% blocktranslate %}Aktuell haben wir {{ruck_veranst}} Rückmeldungen von {{all_veranst}} Veranstaltungen.{% endblocktranslate %}</p>
    <div style="width:{{width_progressbar}}px; background-color:#eeeeec;">
        <div style="width:{{width_progressbar_success}}px; background-color:#babdb6;">
            <p style="text-align:center;">{{relativ_result|floatformat:-2}}%</p>
        </div>
    </div>
    <h3>{% translate "Ablauf" %}</h3>
    <p>{% blocktranslate %}Dies sind nicht alle nötigen Schritte; siehe <a href="https://www.d120.de/bookstack/books/feedback/page/feedback-ablauf%C3%BCbersicht" target="_blank">Ablauf im bookstack</a>.{% endblocktranslate %}</p>

    <ol>
        <li><a href="{% url 'admin:feedback_semester_add' %}" target="_blank">{% translate "neues Semester anlegen" %}</a> ({% translate "aktuell" %}:
        {% if cur_semester %}{{cur_semester.short}}{% else %}{% translate "nicht Vorhanden" %}{% endif %})</li>
        <li><a href="{% url 'feedback:import_vv' %}">{% translate "Veranstaltungen aus VV importieren" %}</a> ({% translate "vor Bestellphase" %})</li>
        <li><a href="{% url 'feedback:import_vv_edit_users' %}">{% translate "Fehlende Personendaten nachtragen" %}</a> ({% translate "vor Bestellphase" %})</li>
        <li><a href="{% url 'feedback:status_final' %}">{% translate "Bestellphase abschließen" %}</a> ({% translate "nach Bestellphase" %})</li>
        <li><a href="{% url 'feedback:generate_letters' %}">{% translate "Anschreiben für Veranstalter erzeugen" %}</a> ({% translate "nach Bestellphase" %})</li>
        <li><a href="{% url 'feedback:export_veranstaltungen' %}">{% translate "Veranstaltungen für EvaSys exportieren" %}</a></li>
        <li><a href="{% url 'feedback:process-tans' %}">{% translate "TANs verarbeiten" %}</a>  ({% translate "nach der Bestellphase" %})</li>
        <li><a href="{% url 'feedback:import_ergebnisse' %}">{% translate "Ergebnisse aus EvaSys importieren" %}</a></li>
        <li><a href="{% url 'feedback:sync_ergebnisse' %}">{% translate "Rankings berechnen" %}</a> ({% translate "nach dem Ergebnis-Import" %})</li>
        {% if cur_semester %}
        <li><a href="{% url 'admin:feedback_semester_change' cur_semester.id %}" target="_blank">{% translate "Ergebnisse veröffentlichen" %}</a>{% blocktranslate %} (aktuell: sichtbar für {{cur_semester.get_sichtbarkeit_display}}){% endblocktranslate %}</li>
        {% endif %}
    </ol>
{% endblock %}

{% block backlink %}<!-- kein Backlink -->{% endblock %}

src/templates/intern/status_final.html
{% extends "bestellung_base.html" %}
{% load i18n %}
{% load static %}
{% block title %}
    {% translate "Interner Bereich" %}
{% endblock %}

{% block content %}
    <h2>{% translate "Bestellphase abschließen" %}?</h2>
    <p>{% translate "Sie sind dabei die Bestellphase zu beenden. Möchten Sie das wirklich tun?" %}</p>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        &nbsp;<input type="submit" name="submit" value="{% translate "Bestätigen" %}" />
    </form>
{% endblock %}