src/feedback/urls.py
# coding=utf-8

from django.conf.urls import include

import feedback.views.public
import feedback.views.veranstalter
from feedback.views.public_class_view import VeranstaltungsDeadlines
import feedback.views.intern
import feedback.views.intern.vv
import feedback.views.intern.auth
from django.views.decorators.csrf import csrf_exempt
import django.contrib.auth.views
from django.urls import reverse_lazy, re_path
from django.conf import settings
from feedback.views.veranstalter import VeranstalterWizard
from django.utils.translation import get_language

default_redirect = f'/{get_language()}/veranstalter/'

# allgemeine Views
urlpatterns = [
    re_path(r'^$', feedback.views.redirect, {'redirect_to': default_redirect}, name="default"),
]

# öffentliche Views
urlpatterns += [
    re_path(r'^ergebnisse/(?P<vid>\d+)/$', feedback.views.public.veranstaltung, name='public-veranstaltung'),
    re_path(r'^ergebnisse/(?P<vid>\d+)/(?P<seminar>seminar)/$', feedback.views.public.veranstaltung, name='public-veranstaltung'),
    re_path(r'^ergebnisse/$', feedback.views.public.index, name='public-results'),
]

urlpatterns += [re_path(r'^deadlines/$', VeranstaltungsDeadlines.as_view(), name='Deadlines'),
                re_path(r'^barcodedrop/$', csrf_exempt(feedback.views.public.barcodedrop), name='barcodedrop'),]


# Veranstalter-Views
urlpatterns += [
    re_path(r'^veranstalter/login/$', feedback.views.veranstalter.login, name='veranstalter-login'),
    re_path(r'^veranstalter/logout/$',
        django.contrib.auth.views.LogoutView.as_view(),
        {'template_name': "veranstalter/logout.html"},
        name='veranstalter-logout'),

    re_path(r'^veranstalter/bestellung', VeranstalterWizard.as_view(), name='veranstalter-bestellung'),
    re_path(r'^veranstalter/', feedback.views.veranstalter.veranstalter_dashboard, name='veranstalter-index')
]

# interne Views
urlpatterns += [
    re_path(r'^intern/uebersicht/$', feedback.views.intern.index, name='intern-index'),
    re_path(r'^intern/sendmail/$', feedback.views.intern.sendmail, name='sendmail'),
    re_path(r'^intern/questions_list/$', feedback.views.intern.freie_frage_veranstaltungen, name='free-questions'),
    re_path(r'^intern/export_veranstaltungen/$', feedback.views.intern.export_veranstaltungen, name='export_veranstaltungen'),
    re_path(r'^intern/generate_letters/$', feedback.views.intern.generate_letters, name='generate_letters'),
    re_path(r'^intern/import_ergebnisse/$', feedback.views.intern.import_ergebnisse, name='import_ergebnisse'),
    re_path(r'^intern/status_final/$', feedback.views.intern.CloseOrderFormView.as_view(), name='status_final'),
    re_path(r'^intern/sync_ergebnisse/$', feedback.views.intern.sync_ergebnisse, name='sync_ergebnisse'),
    re_path(r'^intern/fragebogensprache/$', feedback.views.intern.fragebogensprache, name='fragebogensprache'),
    re_path(r'^intern/lange_ohne_evaluation/$', feedback.views.intern.lange_ohne_evaluation, name='lange_ohne_evaluation'),
    re_path(r'^intern/ergebnisse/$', feedback.views.intern.ergebnisse, name='intern-ergebnisse'),
    re_path(r'^intern/tans/$', feedback.views.intern.ProcessTANs.as_view(),
    name='process-tans'),
]

# interne Views: Vorlesungsverzeichnis
urlpatterns += [
    re_path(r'^intern/import_vv/$', feedback.views.intern.vv.import_vv, name='import_vv'),
    re_path(r'^intern/import_vv_edit/$', feedback.views.intern.vv.import_vv_edit, name='import_vv_edit'),
    re_path(r'^intern/import_vv_edit_users/$', feedback.views.intern.vv.PersonFormView.as_view(),
        name='import_vv_edit_users'),
    re_path(r'^intern/import_vv_edit_users/(?P<pk>\d+)/$', feedback.views.intern.vv.PersonFormUpdateView.as_view(),
        name='import_vv_edit_users_update'),
    re_path(r'^intern/import_vv_edit_users/(?P<pk>\d+)/namecheck/$', feedback.views.intern.vv.SimilarNamesView.as_view(),
        name='import_vv_edit_users_update_namecheck')
]

# interne Views: Authentifizierung
urlpatterns += [
    re_path(r'^intern/rechte_uebernehmen/$', feedback.views.intern.auth.rechte_uebernehmen, name='rechte-uebernehmen'),
    re_path(r'^intern/rechte_zuruecknehmen/$', feedback.views.intern.auth.rechte_zuruecknehmen, name='rechte_zuruecknehmen'),
    re_path(r'^intern/auth_user/$', feedback.views.intern.auth.auth_user, name='auth-user'),
    re_path(r'^intern/$', feedback.views.intern.auth.login, name='auth-login'),
]

# Logout
urlpatterns += [
    re_path(r'^logout/$', django.contrib.auth.views.LogoutView.as_view(), {'next_page': reverse_lazy('feedback:public-results')}, name='logout'),
]


if settings.DEBUG:
    # Ausschließlich in der Entwicklung nötig, damit statische Dateien (JS, CSS, Bilder...)
    # angezeigt werden. Im Server-Betrieb kümmert sich Apache darum.
    urlpatterns += [
        re_path(r'^d120de/(?P<tail>.*)$', feedback.views.redirect, {'redirect_to': 'http://www.d120.de/d120de/'}),
    ]

src/urls.py
# coding=utf-8

from django.conf.urls import include
from django.contrib import admin
from django.contrib.auth.models import User

from django.urls import re_path, reverse_lazy, path
from django.conf.urls.i18n import i18n_patterns
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

from allauth.account.decorators import secure_admin_login

# Admin-Seiten konfigurieren
# admin.site.unregister((User, Group))

# this is a workaround as admin sites doesn't use allauth, see: https://docs.allauth.org/en/latest/common/admin.html
admin.autodiscover()
admin.site.login = secure_admin_login(admin.site.login)

urlpatterns = i18n_patterns(
    path('accounts/', include('allauth.urls')),
)

urlpatterns += [
    re_path(r'^$', RedirectView.as_view(url=reverse_lazy("feedback:default"), permanent=True), name='no-path'),
]

# Datenbank-Admin und Entwicklerdoku
urlpatterns += i18n_patterns(
    # Muss in dieser Reihenfolge stehen bleiben, da sonst /doc nicht funktioniert!
    re_path(r'^intern/admin/doc/', include('django.contrib.admindocs.urls')),
    re_path(r'^intern/admin/', admin.site.urls),
    re_path(r'^', include(("feedback.urls", "feedback"), namespace="feedback")),
)

urlpatterns += staticfiles_urlpatterns()

if not settings.DEBUG :
    # don't forget to put sample favicon.ico in static files
    urlpatterns += [path('favicon.ico', RedirectView.as_view(url='/feedback/static/img/favicon.ico', permanent=True))]

if not settings.TESTING and settings.DEBUG :
    # avoided directly using debug_toolbar.urls(), as importing caused error in django-debug-toolbar v6.0.0 
    # see https://github.com/django-commons/django-debug-toolbar/issues/2167
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

src/templates/bestellung_base.html
{% extends "d120_base.html" %}
{% load i18n %}

{% block section_veranstalter %}
    current
{% endblock %}

{% block backlink %}
    {% if request.user.is_superuser %}
        <p><a href="{% url 'feedback:intern-index' %}">{% translate "zurück zum internen Bereich" %}</a></p>
    {% else %}
        <p><a href="{% url 'feedback:veranstalter-index' %}">{% translate "zurück zum Veranstalterbereich" %}</a></p>
    {% endif %}
{% endblock %}

src/templates/d120_base.html
<?xml version="1.0" encoding="UTF-8"?>{% load static %}{% load i18n %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">

<head>
	<title>{% block title %}{% translate "Leere Seite" %}{% endblock %}{% translate " - Evaluation der Lehre" %}</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />

	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'font-awesome/css/font-awesome.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static '@fontsource/libre-franklin/index.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'custom.css' %}" />
  <style>
      a, footer a:hover, .sidebar-nav a, .sidebar-nav a:hover {
          color:#009D81;
      }
      .header-navbar, .sidebar-active, .sidebar-active:hover, .sidebar-active:focus > a:hover, .sidebar-active > a:focus, #mainLogo {
          background-color:#009D81!important;
      }
      .sidebar-active, .sidebar-active:hover {
          border-left: 5px solid #009D81!important;
      }
  </style>

	<link rel="stylesheet" type="text/css" href="{% static 'ranking.css' %}" /> {% block extra_header %}{% endblock %}
</head>

<body>

	{% include 'd120/header.html' %}
	<div class="container">
		<div id="main" class="row">
			<div class="col-lg-3 col-md-4 col-sm-5">
				{% include 'd120/sidebar.html' %}
			</div>
			<div id="content" class="col-lg-9 col-md-8 col-xs-12 col-sm-7 pull-right typography">

				{% if request.session.orig_uid %}
				<div class="breadcrumbs">
					{% blocktranslate %}Du nutzt momentan die Rechte der Veranstalter von {{veranstaltung}}.{% endblocktranslate %} <a href="{% url 'feedback:rechte_zuruecknehmen' %}">{% translate "Zu meinem Account zurückkehren." %}</a>
				</div>
				{% endif %} {% if messages %}
				<ul class="messagelist">
					{% for message in messages %}
					<li class="{{ message.tags }}">{{ message }}</li>
					{% endfor %}
				</ul>
				{% endif %} {% block content %}{% endblock %}
				<br /> {% block backlink %}{% endblock %}
			</div>
		</div>
	</div>
		{% include 'd120/footer.html' %}
    {% block javascript_block %}
	<script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
	<script src="{% static '@popperjs/core/dist/umd/popper.min.js' %}"></script>
	<script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
    {% endblock %}
</body>

</html>

src/templates/ergebnisse_base.html
{% extends "d120_base.html" %}
{% block section_ergebnisse %}current{% endblock %}