src/feedback/urls.py
# coding=utf-8

from django.conf.urls import include

import feedback.views.public
import feedback.views.veranstalter
from feedback.views.public_class_view import VeranstaltungsDeadlines
import feedback.views.intern
import feedback.views.intern.vv
import feedback.views.intern.auth
from django.views.decorators.csrf import csrf_exempt
import django.contrib.auth.views
from django.urls import reverse_lazy, re_path
from django.conf import settings
from feedback.views.veranstalter import VeranstalterWizard
from django.utils.translation import get_language

default_redirect = f'/{get_language()}/veranstalter/'

# allgemeine Views
urlpatterns = [
    re_path(r'^$', feedback.views.redirect, {'redirect_to': default_redirect}, name="default"),
]

# öffentliche Views
urlpatterns += [
    re_path(r'^ergebnisse/(?P<vid>\d+)/$', feedback.views.public.veranstaltung, name='public-veranstaltung'),
    re_path(r'^ergebnisse/(?P<vid>\d+)/(?P<seminar>seminar)/$', feedback.views.public.veranstaltung, name='public-veranstaltung'),
    re_path(r'^ergebnisse/$', feedback.views.public.index, name='public-results'),
]

urlpatterns += [re_path(r'^deadlines/$', VeranstaltungsDeadlines.as_view(), name='Deadlines'),
                re_path(r'^barcodedrop/$', csrf_exempt(feedback.views.public.barcodedrop), name='barcodedrop'),]


# Veranstalter-Views
urlpatterns += [
    re_path(r'^veranstalter/login/$', feedback.views.veranstalter.login, name='veranstalter-login'),
    re_path(r'^veranstalter/logout/$',
        django.contrib.auth.views.LogoutView.as_view(),
        {'template_name': "veranstalter/logout.html"},
        name='veranstalter-logout'),

    re_path(r'^veranstalter/bestellung', VeranstalterWizard.as_view(), name='veranstalter-bestellung'),
    re_path(r'^veranstalter/', feedback.views.veranstalter.veranstalter_dashboard, name='veranstalter-index')
]

# interne Views
urlpatterns += [
    re_path(r'^intern/uebersicht/$', feedback.views.intern.index, name='intern-index'),
    re_path(r'^intern/sendmail/$', feedback.views.intern.sendmail, name='sendmail'),
    re_path(r'^intern/questions_list/$', feedback.views.intern.freie_frage_veranstaltungen, name='free-questions'),
    re_path(r'^intern/export_veranstaltungen/$', feedback.views.intern.export_veranstaltungen, name='export_veranstaltungen'),
    re_path(r'^intern/generate_letters/$', feedback.views.intern.generate_letters, name='generate_letters'),
    re_path(r'^intern/import_ergebnisse/$', feedback.views.intern.import_ergebnisse, name='import_ergebnisse'),
    re_path(r'^intern/status_final/$', feedback.views.intern.CloseOrderFormView.as_view(), name='status_final'),
    re_path(r'^intern/sync_ergebnisse/$', feedback.views.intern.sync_ergebnisse, name='sync_ergebnisse'),
    re_path(r'^intern/fragebogensprache/$', feedback.views.intern.fragebogensprache, name='fragebogensprache'),
    re_path(r'^intern/lange_ohne_evaluation/$', feedback.views.intern.lange_ohne_evaluation, name='lange_ohne_evaluation'),
    re_path(r'^intern/ergebnisse/$', feedback.views.intern.ergebnisse, name='intern-ergebnisse'),
    re_path(r'^intern/tans/$', feedback.views.intern.ProcessTANs.as_view(),
    name='process-tans'),
]

# interne Views: Vorlesungsverzeichnis
urlpatterns += [
    re_path(r'^intern/import_vv/$', feedback.views.intern.vv.import_vv, name='import_vv'),
    re_path(r'^intern/import_vv_edit/$', feedback.views.intern.vv.import_vv_edit, name='import_vv_edit'),
    re_path(r'^intern/import_vv_edit_users/$', feedback.views.intern.vv.PersonFormView.as_view(),
        name='import_vv_edit_users'),
    re_path(r'^intern/import_vv_edit_users/(?P<pk>\d+)/$', feedback.views.intern.vv.PersonFormUpdateView.as_view(),
        name='import_vv_edit_users_update'),
    re_path(r'^intern/import_vv_edit_users/(?P<pk>\d+)/namecheck/$', feedback.views.intern.vv.SimilarNamesView.as_view(),
        name='import_vv_edit_users_update_namecheck')
]

# interne Views: Authentifizierung
urlpatterns += [
    re_path(r'^intern/rechte_uebernehmen/$', feedback.views.intern.auth.rechte_uebernehmen, name='rechte-uebernehmen'),
    re_path(r'^intern/rechte_zuruecknehmen/$', feedback.views.intern.auth.rechte_zuruecknehmen, name='rechte_zuruecknehmen'),
    re_path(r'^intern/auth_user/$', feedback.views.intern.auth.auth_user, name='auth-user'),
    re_path(r'^intern/$', feedback.views.intern.auth.login, name='auth-login'),
]

# Logout
urlpatterns += [
    re_path(r'^logout/$', django.contrib.auth.views.LogoutView.as_view(), {'next_page': reverse_lazy('feedback:public-results')}, name='logout'),
]


if settings.DEBUG:
    # Ausschließlich in der Entwicklung nötig, damit statische Dateien (JS, CSS, Bilder...)
    # angezeigt werden. Im Server-Betrieb kümmert sich Apache darum.
    urlpatterns += [
        re_path(r'^d120de/(?P<tail>.*)$', feedback.views.redirect, {'redirect_to': 'http://www.d120.de/d120de/'}),
    ]

src/urls.py
# coding=utf-8

from django.conf.urls import include
from django.contrib import admin
from django.contrib.auth.models import User

from django.urls import re_path, reverse_lazy, path
from django.conf.urls.i18n import i18n_patterns
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

from allauth.account.decorators import secure_admin_login

# Admin-Seiten konfigurieren
# admin.site.unregister((User, Group))

# this is a workaround as admin sites doesn't use allauth, see: https://docs.allauth.org/en/latest/common/admin.html
admin.autodiscover()
admin.site.login = secure_admin_login(admin.site.login)

urlpatterns = i18n_patterns(
    path('accounts/', include('allauth.urls')),
)

urlpatterns += [
    re_path(r'^$', RedirectView.as_view(url=reverse_lazy("feedback:default"), permanent=True), name='no-path'),
]

# Datenbank-Admin und Entwicklerdoku
urlpatterns += i18n_patterns(
    # Muss in dieser Reihenfolge stehen bleiben, da sonst /doc nicht funktioniert!
    re_path(r'^intern/admin/doc/', include('django.contrib.admindocs.urls')),
    re_path(r'^intern/admin/', admin.site.urls),
    re_path(r'^', include(("feedback.urls", "feedback"), namespace="feedback")),
)

urlpatterns += staticfiles_urlpatterns()

if not settings.DEBUG :
    # don't forget to put sample favicon.ico in static files
    urlpatterns += [path('favicon.ico', RedirectView.as_view(url='/feedback/static/img/favicon.ico', permanent=True))]

if not settings.TESTING and settings.DEBUG :
    # avoided directly using debug_toolbar.urls(), as importing caused error in django-debug-toolbar v6.0.0 
    # see https://github.com/django-commons/django-debug-toolbar/issues/2167
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

src/templates/d120/footer.html
{% load i18n %}

<footer class="footer">
    <div class="container">
        <div class="footer-column">
            <div class="footer-group">
                <p><a href="https://www.fachschaft.informatik.tu-darmstadt.de">{% translate "Startseite" %}</a></p>
                <p><a href="https://www.fachschaft.informatik.tu-darmstadt.de/kontakt">{% translate "Kontakt" %}</a></p>
                <p><a href="https://www.fachschaft.informatik.tu-darmstadt.de/impressum">{% translate "Impressum" %}</a></p>
		<p><a href="https://www.fachschaft.informatik.tu-darmstadt.de/datenschutz">{% translate "Datenschutzerklärung" %}</a></p>
            </div>
            <div class="footer-group">
                <p><a href="https://github.com/d120" aria-label="Github"><i class="fa fa-fw fa-github" aria-hidden="true" title="Github"></i></a></p>
            </div>
            <div class="footer-group">
                &copy; Fachschaft Informatik TU Darmstadt
            </div>
        </div>
    </div>
</footer>

src/templates/d120/header.html
{% load i18n %}
{% load static %}
{% load translate_url %}
<nav class="navbar navbar-logos">
  <div class="container" id="header">
    <a href="https://www.fachschaft.informatik.tu-darmstadt.de">
      <img src="{% static 'img/d120_logo.png' %}" id="mainLogo" alt="D120: Fachschaft Informatik" class="pull-left" />
    </a>
    <a href="https://www.tu-darmstadt.de" id="responsivelogo">
      <img src="{% static 'img/tu_da_logo.png' %}" alt="Technische Universität Darmstadt" class="pull-right" />
    </a>
  </div>
</nav>
<nav class="navbar navbar-expand header-navbar" id="colored-navbar">
    <div class="container justify-content-end">
        <ul class="nav navbar-nav">
            <li class="nav-item header-navbar-item">
                <a class="nav-link header-navbar-link" href="https://www.fachschaft.informatik.tu-darmstadt.de">
                    <i class="fa fa-home fa-lg"></i> <span class="d-none d-sm-inline">{% translate "Webseite" %}</span>
                </a>
            </li>
            <li class="nav-item header-navbar-item">
                <a class="nav-link header-navbar-link" href="https://www.informatik.tu-darmstadt.de">
                    <i class="fa fa-university fa-lg"></i> <span class="d-none d-sm-inline">{% translate "Fachbereich" %}</span>
                </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link header-navbar-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    {% get_current_language as CURRENT_LANG %}
                    {% get_language_info for CURRENT_LANG as lang %}
                    <i class="fa fa-globe fa-lg"></i> <span class="d-none d-sm-inline">{{ lang.name_local }}</span>
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% for language in languages %}
                        <li><a class="dropdown-item" href="{% translate_url language.code %}" style="color: black;">{{ language.name_local }}</a></li>
                    {% endfor %}
                </ul>
            </li>
        </ul>
    </div>
</nav>

src/templates/d120/sidebar.html
{% load i18n %}
<nav class="navbar navbar-light">
<div id="sidebar" class="collapse navbar-collapse d-sm-inline">
<ul class="nav sidebar-nav flex-column">
  <li class="nav-item sidebar-active">
    <a href="https://www.fachschaft.informatik.tu-darmstadt.de/feedback-new/" title="Gehe zur Seite &quot;Feedback&quot;">{% translate "Feedback" %}</a>
    <ul id="menuIndent">
      <li class="nva-item link">
        <a href="https://www.fachschaft.informatik.tu-darmstadt.de/feedback-faq/" title="Zeige Seite FAQ">{% translate "FAQ" %}</a>
      </li>
      <li class="nav-item link">
        <a href="https://www.fachschaft.informatik.tu-darmstadt.de/hall-of-fame/" title="Zeige Seite Hall of Fame">{% translate "Hall of Fame" %}</a>
      </li>
      <li class="nav-item {% block section_ergebnisse %}link{% endblock %}">
        <a href="{% if request.user.is_superuser %}{% url 'feedback:intern-ergebnisse' %}{% else %}{% url 'feedback:public-results' %}{% endif %}" title="Zeige Seite Ergebnisse">{% translate "Ergebnisse" %}</a>
      </li>
      <li class="nav-item {% block section_veranstalter %}link{% endblock %}">
        <a href="{% url 'feedback:veranstalter-index' %}" title="Zeige Seite Webinterface">{% translate "Webinterface" %}</a>
      </li>
    </ul>
  </li>
</ul>
</div>
</nav>