src/feedback/urls.py
# coding=utf-8

from django.conf.urls import include

import feedback.views.public
import feedback.views.veranstalter
from feedback.views.public_class_view import VeranstaltungsDeadlines
import feedback.views.intern
import feedback.views.intern.vv
import feedback.views.intern.auth
from django.views.decorators.csrf import csrf_exempt
import django.contrib.auth.views
from django.urls import reverse_lazy, re_path
from django.conf import settings
from feedback.views.veranstalter import VeranstalterWizard
from django.utils.translation import get_language

default_redirect = f'/{get_language()}/veranstalter/'

# allgemeine Views
urlpatterns = [
    re_path(r'^$', feedback.views.redirect, {'redirect_to': default_redirect}, name="default"),
]

# öffentliche Views
urlpatterns += [
    re_path(r'^ergebnisse/(?P<vid>\d+)/$', feedback.views.public.veranstaltung, name='public-veranstaltung'),
    re_path(r'^ergebnisse/(?P<vid>\d+)/(?P<seminar>seminar)/$', feedback.views.public.veranstaltung, name='public-veranstaltung'),
    re_path(r'^ergebnisse/$', feedback.views.public.index, name='public-results'),
]

urlpatterns += [re_path(r'^deadlines/$', VeranstaltungsDeadlines.as_view(), name='Deadlines'),
                re_path(r'^barcodedrop/$', csrf_exempt(feedback.views.public.barcodedrop), name='barcodedrop'),]


# Veranstalter-Views
urlpatterns += [
    re_path(r'^veranstalter/login/$', feedback.views.veranstalter.login, name='veranstalter-login'),
    re_path(r'^veranstalter/logout/$',
        django.contrib.auth.views.LogoutView.as_view(),
        {'template_name': "veranstalter/logout.html"},
        name='veranstalter-logout'),

    re_path(r'^veranstalter/bestellung', VeranstalterWizard.as_view(), name='veranstalter-bestellung'),
    re_path(r'^veranstalter/', feedback.views.veranstalter.veranstalter_dashboard, name='veranstalter-index')
]

# interne Views
urlpatterns += [
    re_path(r'^intern/uebersicht/$', feedback.views.intern.index, name='intern-index'),
    re_path(r'^intern/sendmail/$', feedback.views.intern.sendmail, name='sendmail'),
    re_path(r'^intern/questions_list/$', feedback.views.intern.freie_frage_veranstaltungen, name='free-questions'),
    re_path(r'^intern/export_veranstaltungen/$', feedback.views.intern.export_veranstaltungen, name='export_veranstaltungen'),
    re_path(r'^intern/generate_letters/$', feedback.views.intern.generate_letters, name='generate_letters'),
    re_path(r'^intern/import_ergebnisse/$', feedback.views.intern.import_ergebnisse, name='import_ergebnisse'),
    re_path(r'^intern/status_final/$', feedback.views.intern.CloseOrderFormView.as_view(), name='status_final'),
    re_path(r'^intern/sync_ergebnisse/$', feedback.views.intern.sync_ergebnisse, name='sync_ergebnisse'),
    re_path(r'^intern/fragebogensprache/$', feedback.views.intern.fragebogensprache, name='fragebogensprache'),
    re_path(r'^intern/lange_ohne_evaluation/$', feedback.views.intern.lange_ohne_evaluation, name='lange_ohne_evaluation'),
    re_path(r'^intern/ergebnisse/$', feedback.views.intern.ergebnisse, name='intern-ergebnisse'),
    re_path(r'^intern/tans/$', feedback.views.intern.ProcessTANs.as_view(),
    name='process-tans'),
]

# interne Views: Vorlesungsverzeichnis
urlpatterns += [
    re_path(r'^intern/import_vv/$', feedback.views.intern.vv.import_vv, name='import_vv'),
    re_path(r'^intern/import_vv_edit/$', feedback.views.intern.vv.import_vv_edit, name='import_vv_edit'),
    re_path(r'^intern/import_vv_edit_users/$', feedback.views.intern.vv.PersonFormView.as_view(),
        name='import_vv_edit_users'),
    re_path(r'^intern/import_vv_edit_users/(?P<pk>\d+)/$', feedback.views.intern.vv.PersonFormUpdateView.as_view(),
        name='import_vv_edit_users_update'),
    re_path(r'^intern/import_vv_edit_users/(?P<pk>\d+)/namecheck/$', feedback.views.intern.vv.SimilarNamesView.as_view(),
        name='import_vv_edit_users_update_namecheck')
]

# interne Views: Authentifizierung
urlpatterns += [
    re_path(r'^intern/rechte_uebernehmen/$', feedback.views.intern.auth.rechte_uebernehmen, name='rechte-uebernehmen'),
    re_path(r'^intern/rechte_zuruecknehmen/$', feedback.views.intern.auth.rechte_zuruecknehmen, name='rechte_zuruecknehmen'),
    re_path(r'^intern/auth_user/$', feedback.views.intern.auth.auth_user, name='auth-user'),
    re_path(r'^intern/$', feedback.views.intern.auth.login, name='auth-login'),
]

# Logout
urlpatterns += [
    re_path(r'^logout/$', django.contrib.auth.views.LogoutView.as_view(), {'next_page': reverse_lazy('feedback:public-results')}, name='logout'),
]


if settings.DEBUG:
    # Ausschließlich in der Entwicklung nötig, damit statische Dateien (JS, CSS, Bilder...)
    # angezeigt werden. Im Server-Betrieb kümmert sich Apache darum.
    urlpatterns += [
        re_path(r'^d120de/(?P<tail>.*)$', feedback.views.redirect, {'redirect_to': 'http://www.d120.de/d120de/'}),
    ]

src/urls.py
# coding=utf-8

from django.conf.urls import include
from django.contrib import admin
from django.contrib.auth.models import User

from django.urls import re_path, reverse_lazy, path
from django.conf.urls.i18n import i18n_patterns
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

from allauth.account.decorators import secure_admin_login

# Admin-Seiten konfigurieren
# admin.site.unregister((User, Group))

# this is a workaround as admin sites doesn't use allauth, see: https://docs.allauth.org/en/latest/common/admin.html
admin.autodiscover()
admin.site.login = secure_admin_login(admin.site.login)

urlpatterns = i18n_patterns(
    path('accounts/', include('allauth.urls')),
)

urlpatterns += [
    re_path(r'^$', RedirectView.as_view(url=reverse_lazy("feedback:default"), permanent=True), name='no-path'),
]

# Datenbank-Admin und Entwicklerdoku
urlpatterns += i18n_patterns(
    # Muss in dieser Reihenfolge stehen bleiben, da sonst /doc nicht funktioniert!
    re_path(r'^intern/admin/doc/', include('django.contrib.admindocs.urls')),
    re_path(r'^intern/admin/', admin.site.urls),
    re_path(r'^', include(("feedback.urls", "feedback"), namespace="feedback")),
)

urlpatterns += staticfiles_urlpatterns()

if not settings.DEBUG :
    # don't forget to put sample favicon.ico in static files
    urlpatterns += [path('favicon.ico', RedirectView.as_view(url='/feedback/static/img/favicon.ico', permanent=True))]

if not settings.TESTING and settings.DEBUG :
    # avoided directly using debug_toolbar.urls(), as importing caused error in django-debug-toolbar v6.0.0 
    # see https://github.com/django-commons/django-debug-toolbar/issues/2167
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

src/feedback/views/veranstalter.py
# coding=utf-8

from django import forms
from django.conf import settings
from django.views.decorators.http import require_safe
from django.contrib import auth
from django.http import HttpRequest, HttpResponseRedirect, Http404
from django.urls import reverse
from django.shortcuts import render
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.translation import gettext_lazy as _
from django.contrib import messages

from formtools.wizard.views import SessionWizardView
from feedback.models import Veranstaltung, Tutor, past_semester_orders, Log
from feedback.forms import VeranstaltungEvaluationForm, VeranstaltungBasisdatenForm, \
    VeranstaltungFreieFragen, VeranstaltungVeroeffentlichung, VeranstaltungDigitaleEvaluationForm, VeranstaltungAnzahlForm


@require_safe
def login(request):
    if 'vid' in request.GET and 'token' in request.GET:
        vid = int(request.GET['vid'])
        token = str(request.GET['token'])

        user = auth.authenticate(vid=vid, token=token)
        if user:
            auth.login(request, user)
            v = Veranstaltung.objects.get(id=vid)
            request.session['vid'] = v.id
            request.session['veranstaltung'] = str(v)

            return HttpResponseRedirect(reverse('feedback:veranstalter-index'))

    return render(request, 'veranstalter/login_failed.html')


def veranstalter_dashboard(request):
    """Definiert den Dashboard für die Veranstalter-View."""
    if request.user.username != settings.USERNAME_VERANSTALTER:
        return render(request, 'veranstalter/not_authenticated.html')

    data = {}
    veranst = Veranstaltung.objects.get(id=request.session['vid'])

    data["veranstaltung"] = veranst
    data["logs"] = Log.objects.filter(veranstaltung=veranst).order_by('timestamp')
    data["allow_order"] = veranst.allow_order()

    if veranst.status >= Veranstaltung.STATUS_BESTELLUNG_LIEGT_VOR:
        bestellung = [(_("Evaluieren"), veranst.get_evaluieren_display)]
        if veranst.evaluieren:
            bestellung.append((_("Typ"), veranst.get_typ_display))
            bestellung.append((_("Anazhl"), veranst.anzahl))
            bestellung.append((_("Sprache"), veranst.get_sprache_display))
            bestellung.append((_("Verantwortlich"), veranst.verantwortlich.__str__() + '\n'
                               + veranst.verantwortlich.anschrift + '\n'
                               + veranst.verantwortlich.email))

            ergebnis_empfanger_str = ""
            for empfaenger in veranst.ergebnis_empfaenger.all():
                ergebnis_empfanger_str += empfaenger.__str__() + "\n"
            bestellung.append((_("Ergebnis Empfänger"), ergebnis_empfanger_str))

            if veranst.auswertungstermin:
                bestellung.append((_("Auswertungstermin"), veranst.auswertungstermin))

            bestellung.append((_("Primärdozent"), veranst.primaerdozent))
            bestellung.append((_("Freie Frage 1"), veranst.freiefrage1))
            bestellung.append((_("Freie Frage 2"), veranst.freiefrage2))
            bestellung.append((_("Veröffentlichen"), veranst.get_veroeffentlichen_display))

        data["bestellung"] = bestellung

    return render(request, 'veranstalter/dashboard.html', data)


# ---------------------------------------- START WIZARD ---------------------------------------- #

# Alle Templates, die vom Wizard gebraucht werden.
VERANSTALTER_VIEW_TEMPLATES = {
    "anzahl" : "formtools/wizard/anzahl.html",
    "evaluation": "formtools/wizard/evaluation.html",
    "basisdaten": "formtools/wizard/basisdaten.html",
    "digitale_eval": "formtools/wizard/digitale_evaluation.html",
    "freie_fragen": "formtools/wizard/freiefragen.html",
    "veroeffentlichen": "formtools/wizard/veroeffentlichen.html",
    "zusammenfassung": "formtools/wizard/zusammenfassung.html"
}

# Alle Schritte, die vom Wizard gebraucht werden.
VERANSTALTER_WIZARD_STEPS = {
    "anzahl" : _("Anzahl"),
    "evaluation": _("Evaluation"),
    "basisdaten": _("Basisdaten"),
    "digitale_eval": _("Digitale Evaluation"),
    "freie_fragen": _("Freie Fragen"),
    "veroeffentlichen": _("Veroeffentlichen"),
    "zusammenfassung": _("Zusammenfassung")
}


def perform_evalution(wizard):
    """
    Checks if user has choosen to evaluate, default returns True
    """
    wizard.cached_obj["cleaned_data_evaluation"] = wizard.get_cleaned_data_for_step('evaluation') or {}
    cleaned_data = wizard.cached_obj["cleaned_data_evaluation"]

    return cleaned_data.get('evaluieren', True)

def vollerhebung_check(wizard) :
    """
    Checks if the semester is a vollerhebung semester
    """
    v = wizard.get_instance()

    return v.semester.vollerhebung

def order_amount_check(wizard) :
    """
    Checks if amount of orders greater than or equal to MIN_BESTELLUNG_ANZAHL
    """
    wizard.cached_obj["cleaned_data_anzahl"] = wizard.get_cleaned_data_for_step('anzahl') or {}
    cleaned_data = wizard.cached_obj["cleaned_data_anzahl"]

    return cleaned_data.get('anzahl', 0) >= Veranstaltung.MIN_BESTELLUNG_ANZAHL

def activate_step(wizard, step) :
    """
    Checks if given step should be shown in the form
    """
    vollerhebung = vollerhebung_check(wizard)
    amount = order_amount_check(wizard)
    evaluation = perform_evalution(wizard)

    if step == "basisdaten" :
        return (evaluation or vollerhebung) and amount
    elif step == "digitale_eval" :
        return (evaluation or vollerhebung) and amount
    elif step == "freie_fragen" :
        return (evaluation or vollerhebung) and amount
    elif step == "veroeffentlichen" :
        return (evaluation or vollerhebung) and amount
    
    return True

def swap(collection, i, j):
    """Einfache Swap-Funktion, die für die Darstellung von Daten in der Zusammenfassung gebraucht wird."""
    # swap elements of summary data and ignore IndexError of no evaluation
    try:
        collection[i], collection[j] = collection[j], collection[i]
    except IndexError:
        pass


class VeranstalterWizard(SessionWizardView):
    """Definiert den Wizard für den Bestellprozess."""
    form_list = [
        ('anzahl', VeranstaltungAnzahlForm),
        ('evaluation', VeranstaltungEvaluationForm),
        ('basisdaten', VeranstaltungBasisdatenForm),
        ('digitale_eval', VeranstaltungDigitaleEvaluationForm),
        ('freie_fragen', VeranstaltungFreieFragen),
        ('veroeffentlichen', VeranstaltungVeroeffentlichung),
        ('zusammenfassung', forms.Form)
    ]

    condition_dict = {
        'basisdaten': lambda wizard : activate_step(wizard, 'basisdaten'),
        'digitale_eval': lambda wizard : activate_step(wizard, 'digitale_eval'),
        'freie_fragen': lambda wizard : activate_step(wizard, 'freie_fragen'),
        'veroeffentlichen': lambda wizard : activate_step(wizard, 'veroeffentlichen'),
    }

    cached_obj = {}

    def process_step(self, form):
        step = self.steps.current
        request = self.request

        if step == 'anzahl' :
            anzahl_data = form.cleaned_data.get('anzahl', 0)
            if anzahl_data < Veranstaltung.MIN_BESTELLUNG_ANZAHL :
                messages.info(request, Veranstaltung.anzahl_too_few_msg())

        elif step == 'evaluation' :
            if not order_amount_check(self) :
                messages.error(self.request, Veranstaltung.anzahl_too_few_msg())

        return super().process_step(form)
    
    def dispatch(self, request, *args, **kwargs):
        self.cached_obj = {}
        return super(VeranstalterWizard, self).dispatch(request, *args, **kwargs)

    def get_instance(self):
        if self.cached_obj.get("veranstaltung_obj", None) is None:
            if 'vid' not in self.request.session:
                raise Http404(_('Ihre Session ist abgelaufen. Bitte loggen Sie sich erneut über den Link ein.'))
            self.cached_obj["veranstaltung_obj"] = Veranstaltung.objects.\
                select_related().filter(id=self.request.session['vid'])[0]
        return self.cached_obj["veranstaltung_obj"]

    def get_all_veranstalter(self):
        if self.cached_obj.get("all_veranstalter", None) is None:
            self.cached_obj["all_veranstalter"] = self.get_instance().veranstalter.all()
        return self.cached_obj["all_veranstalter"]

    def get_cleaned_basisdaten(self):
        if not self.cached_obj.get("cleaned_data_basisdaten", {}):
            self.cached_obj["cleaned_data_basisdaten"] = self.get_cleaned_data_for_step('basisdaten') or {}
        return self.cached_obj["cleaned_data_basisdaten"]

    def get(self, request, *args, **kwargs):
        if self.request.user.username != settings.USERNAME_VERANSTALTER:
            return render(self.request, 'veranstalter/not_authenticated.html')
        veranstaltung = self.get_instance()
        if veranstaltung.allow_order():
            return super(VeranstalterWizard, self).get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('feedback:veranstalter-index'))

    def get_context_data(self, form, **kwargs):
        context = super(VeranstalterWizard, self).get_context_data(form=form, **kwargs)
        context.update({'veranstaltung': self.get_instance()})

        progressbar = []
        step_active = True
        for step_key in self.get_form_list():
            progressbar.append({
                'step_value': VERANSTALTER_WIZARD_STEPS[step_key],
                'step_active': step_active,
                'step_key': step_key if step_key in self.steps.all else None
            })
            if step_active:
                if step_key == self.steps.current:
                    step_active = False
        context.update({'progressbar': progressbar})

        if self.steps.current == "basisdaten":
            past_sem_data = past_semester_orders(self.get_instance())
            context.update({'past_semester_data': past_sem_data})

        if self.steps.current == "zusammenfassung":

src/templates/veranstalter/dashboard.html
{% extends "d120_base.html" %}
{% load static %}
{% load i18n %}

{% block title %}
    {% translate "Veranstalterbereich" %}
{% endblock %}

{% block extra_header %}
    <style>
        .header_veranst {
            color: #5b5b5b;
        }
        .subHeaderDashboard {
            margin: 15px 0px;
            font-size: 13px;
            font-weight: bold;

        }
        .borderLine {
            border: 1px solid #767676;
            padding: 5px;
        }
        .dashboardTable {
            font-size: 13px;
            margin: 0px;
            padding: 5px;
        }
        .dashboardTableBordered {
            border: 1px solid #767676;
        }
        .dashboardTable td {
            padding: 10px;
            text-align: left;
        }
        .dashboardTable th {
            text-align: left;
            padding: 3px 5px;
            vertical-align: top;
        }
        .dashboardOrderContainer {
            display: inline-block;
        }
        .tableTutoren td {
            font-weight: normal;
        }
        .orderHeadContainer .orderButton {
            margin-top: 14px;
            margin-left: 10px;
            padding: 2px;
        }
        .orderHeadContainer {
            overflow: hidden;
        }
    </style>
{% endblock %}

{% block content %}

    <h1>
        <span class="header_veranst">{{ veranstaltung.name }} - </span>
        {% translate "Dashboard" %}
    </h1>

    <form action = "{% url 'feedback:veranstalter-logout' %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-link p-0" style="color: #009D81;">{% translate "Ausloggen" %}</button>
    </form>

    <p class="subHeaderDashboard">{% translate "Status" %}</p>
    <span class="borderLine">{{ veranstaltung.get_status_display }}</span>

    <p class="subHeaderDashboard">{% translate "Log" %}</p>
    <table class="dashboardTable dashboardTableBordered">
        <tr>
            <th>{% translate "Datum" %}</th>
            <th>{% translate "Status" %}</th>
        </tr>
        {% for log in logs %}
        <tr>
            <td>{{ log.timestamp }}</td>
            <td>{{ log.get_status_display }}</td>
        </tr>
        {% endfor %}
    </table>

    {% if bestellung %}
        <div class="orderHeadContainer">
            <span style="display: block; float: left" class="subHeaderDashboard">{% translate "Aktuelle Bestellung" %}</span>
            {% if allow_order %}
                <button class="orderButton" onclick="window.location='{% url 'feedback:veranstalter-bestellung' %}';">{% translate "Bestellung ändern" %}</button>
            {% endif %}
        </div>
        <div class="dashboardOrderContainer dashboardTableBordered">

            <table class="dashboardTable">
                {% for row in bestellung %}
                <tr>
                    <th>{{ row.0 }}</th>
                    <td>{{ row.1 | linebreaksbr}}</td>
                </tr>
                {% endfor %}
                {% if tutoren %}
                <tr>
                    <th>{% translate "Tutoren" %}</th>
                    <th>
                        <table class="tableTutoren">
                            <tr>
                                <th>{% translate "Num" %}</th>
                                <th>{% translate "Vorname" %}</th>
                                <th>{% translate "Nachname" %}</th>
                                <th>{% translate "Email" %}</th>
                                <th>{% translate "Anmerkung" %}</th>
                            </tr>
                            {% for tutor in tutoren %}
                                <tr>
                                    <td>{{ tutor.nummer }}</td>
                                    <td>{{ tutor.vorname }}</td>
                                    <td>{{ tutor.nachname }}</td>
                                    <td>{{ tutor.email }}</td>
                                    <td>{{ tutor.anmerkung }}</td>
                                </tr>
                            {% endfor %}
                        </table>
                    </th>
                </tr>
                {% endif %}
            </table>
        </div>
    {% else %}
        {% if allow_order %}
            <button style="padding: 2px; background-color: #4CAF50; margin:2px; color:white; border: 1px solid black;" onclick="window.location='{% url 'feedback:veranstalter-bestellung' %}';">{% translate "Bestellung durchführen" %}</button>
        {% endif %}
    {% endif %}


{% endblock %}
{% block backlink %}
    <!-- kein Backlink -->
{% endblock %}

{% block javascript_block %}
<script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
<script src="{% static '@popperjs/core/dist/umd/popper.min.js' %}"></script>
<script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script>
    {% if bestellung %}
    $(document).ready(function() {
        create_csv_table(
                $("#table_tutoren_csvview"),
                $("#table_tutoren_csvview").val()
        );
    });
    {% endif %}
</script>
{% endblock %}

src/templates/veranstalter/index.html
{% extends "bestellung_base.html" %}
{% load i18n %}
{% block title %}
    {% translate "Veranstalterbereich" %}
{% endblock %}
{% block content %}

    <h1>{% translate "Herzlich willkommen!" %}</h1>

    <p>
        {% blocktranslate %}eingeloggt für <strong>{{veranstaltung.name}} ({{veranstaltung.semester.short}})</strong>{% endblocktranslate %}
	    <br />
        <form action = "{% url 'feedback:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-link p-0" style="color: #009D81;">{% translate "ausloggen" %}</button>
        </form>
    </p>

    {% if order_form and veranstaltung.semester.vollerhebung %}
        <h2>{% translate "Information zur Vollerhebung" %}</h2>
        {% blocktranslate %}
        In diesem Semester findet eine Vollerhebung aller Lehrveranstaltungen am Fachbereich Informatik statt.
        Die Teilnahme an der Evaluation der Lehre ist somit laut §4 Abs. 9 Richtlinien für den Bereich der
        Lehrveranstaltungsevaluation der Technischen Universität Darmstadt veröffentlicht in der
        <a href="https://www.intern.tu-darmstadt.de/media/dezernat_ii/satzungsbeilagen/sb_14_III.pdf">Satzungsbeilage 2014-III</a>
        <strong>verpflichtend</strong> für alle Lehrveranstaltungen. Falls Ihre Veranstaltung eine Service-Veranstaltung
        ist und die Evaluation durch einen anderen Fachbereich durchgeführt wird setzen Sie sich bitte mit uns in Verbindung:
        <a href="mailto:feedback@fachschaft.informatik.tu-darmstadt.de">feedback@fachschaft.informatik.tu-darmstadt.de</a>
        {% endblocktranslate %}
    {% endif %}

    <h2>{% translate "Fragebogenbestellung Schritt 1 von 5" %}</h2>
    <h3>{% translate "Ablauf" %}</h3>

    <ol>
	    <li><strong>{% translate "Basisdaten" %}</strong></li>
	    <li>{% translate "Datenüberprüfung" %}</li>
	    <li>{% translate "Freie Fragen" %}</li>
	    <li>{% translate "Details zur Übung" %}</li>
	    <li>{% translate "Zusammenfassung" %}</li>
    </ol>

    <h3>{% translate "Basisdaten" %}</h3>
    {% if not order_form %}
        <p>
            {% translate "Im Moment können keine Fragebögen bestellt werden. Sie erhalten eine E-Mail, sobald dies wieder möglich ist." %}
        </p>
    {% else %}
        <p>{% translate "Bitte geben Sie an, wie viele Fragebögen Sie in welcher Sprache benötigen." %}
            {% if paper_dict|length > 0 %}
                {% translate "Zur Orientierung finden Sie hier die Anzahl bestellter und ausgefüllter Bögen vergangener Semester:" %}</p>
                <table>
                    <tr>
                        <th>{% translate "Semester" %}</th>
                        <th>{% translate "Bestellte Bögen" %}</th>
                        <th>{% translate "Ausgefüllte Bögen" %}</th>
                    </tr>
                    {% for cur_sem in paper_dict %}
                        <tr>
                            <td>{{ cur_sem.veranstaltung.semester }}</td>
                            <td>{{ cur_sem.anzahl_bestellung }}</td>
                            <td>{{ cur_sem.anzahl_ruecklauf }}</td>
                        </tr>
                    {% endfor %}
                </table>
            {% else %}
                </p>
            {% endif %}


        <form action="" method="post" enctype="multipart/form-data" accept-charset="utf-8">
            {% csrf_token %}
            <table>{{order_form}}</table>
	        <div>
		        <input type="submit" name="submit" value="{% translate "Weiter" %}" />&nbsp;
		        <input type="reset" name="reset" value="{% translate "Zurücksetzen" %}" />
	        </div>
        </form>
    {% endif %}


    <h2>{% translate "Kommentar" %}</h2>
    {% if not comment_form %}
        <p>
            {% translate "Für diese Veranstaltung können im Moment noch keine Kommentare verfasst werden.
            Sie erhalten eine E-Mail, sobald dies möglich ist." %}
        </p>
    {% else %}
        <p>{% blocktranslate with ergebnis_url={% url 'feedback:public-veranstaltung' veranstaltung.id %} %}
            Sie können hier einen Kommentar zum
            <a href="{{ergebnis_url}}">Evaluationsergebnis</a> verfassen.
            Dieser Kommentar wird auf der zugehörigen Ergebnis-Seite hochschul-öffentlich angezeigt werden.
            {% endblocktranslate %}
        </p>

        <p>{% translate "Um einen Kommentar wieder zu entfernen, löschen Sie bitte den vorhandenen Kommentartext." %}</p>

        <form action="" method="post" enctype="multipart/form-data" accept-charset="utf-8">
            {% csrf_token %}
	        <table>{{comment_form}}</table>
	        <div>
		        <input type="submit" name="submit" value="{% translate "Speichern" %}" />&nbsp;
		        <input type="reset" name="reset" value="{% translate "Zurücksetzen" %}" />
	        </div>
        </form>
    {% endif %}
{% endblock %}
{% block backlink %}
    <!-- kein Backlink -->
{% endblock %}

src/templates/veranstalter/login_failed.html
{% extends "bestellung_base.html" %}
{% load i18n %}

{% block title %}{% translate "Login fehlgeschlagen" %}{% endblock %}

{% block content %}
<h1>{% translate "Login fehlgeschlagen" %}</h1>

<p>{% blocktranslate %}
Bitte überprüfen Sie, ob der Login-Link aus der E-Mail vollständig in die Adresszeile Ihres
Browsers übertragen wurde. Falls dies der Fall ist und der Login trotzdem fehlschlägt, melden Sie
sich bitte beim <a href="mailto:feedback@fachschaft.informatik.tu-darmstadt.de">Feedback-Team</a>.
Wir bitten für die Unannehmlichkeiten um Entschuldigung.
{% endblocktranslate %}
</p>
{% endblock %}